### ISSUE TITLE
 when i scrolled in the last item the demo  flash back

### ISSUE THREAD

**Issue by sungerk** [VictorAlbertos/RxCacheSamples#1]
i close the network  has the bug
05-12 17:22:55.586 14082-14082/victoralbertos.io.rxjavacache E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: victoralbertos.io.rxjavacache, PID: 14082
                                                                               Theme: themes:{}

**Comment by VictorAlbertos** [comment]
Hi

I've upload some changes, in order to not crash the app when there is no loader available neither cached data.

It happens because the providers endpoints have just 2 minutes of life, so after 2 minutes the data cached will be evicted automatically. The real problem was that the error were not handled on the observable subscription.

Try again with the update, please ;)

**Comment by sungerk** [comment]
thank you ,i will try in my free time
